//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加操作权限 的本地化字符串。
        /// </summary>
        public static string AddAction {
            get {
                return ResourceManager.GetString("AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加角色信息成功 的本地化字符串。
        /// </summary>
        public static string AddRoleInfoSuccess {
            get {
                return ResourceManager.GetString("AddRoleInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用变更 的本地化字符串。
        /// </summary>
        public static string ApplyChange {
            get {
                return ResourceManager.GetString("ApplyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件上传 的本地化字符串。
        /// </summary>
        public static string AttachmentsUpload {
            get {
                return ResourceManager.GetString("AttachmentsUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string BaseInfo {
            get {
                return ResourceManager.GetString("BaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料BOM差异 的本地化字符串。
        /// </summary>
        public static string BomDiffDetail {
            get {
                return ResourceManager.GetString("BomDiffDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料清单 的本地化字符串。
        /// </summary>
        public static string BOMList {
            get {
                return ResourceManager.GetString("BOMList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选择 的本地化字符串。
        /// </summary>
        public static string CancelSelections {
            get {
                return ResourceManager.GetString("CancelSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中所有下级 的本地化字符串。
        /// </summary>
        public static string CheckAllChildren {
            get {
                return ResourceManager.GetString("CheckAllChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空所有选中项 的本地化字符串。
        /// </summary>
        public static string ClearCheckedAll {
            get {
                return ResourceManager.GetString("ClearCheckedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭对话框 的本地化字符串。
        /// </summary>
        public static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭窗口 的本地化字符串。
        /// </summary>
        public static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代号 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中航精机 的本地化字符串。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置完成 的本地化字符串。
        /// </summary>
        public static string CompleteSettings {
            get {
                return ResourceManager.GetString("CompleteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除合件 的本地化字符串。
        /// </summary>
        public static string CompositePiecesCancel {
            get {
                return ResourceManager.GetString("CompositePiecesCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合件操作 的本地化字符串。
        /// </summary>
        public static string CompositePiecesOperation {
            get {
                return ResourceManager.GetString("CompositePiecesOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除合件引用 的本地化字符串。
        /// </summary>
        public static string CompositePiecesQuoteCancel {
            get {
                return ResourceManager.GetString("CompositePiecesQuoteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用合件 的本地化字符串。
        /// </summary>
        public static string CompositePiecesQuoteSet {
            get {
                return ResourceManager.GetString("CompositePiecesQuoteSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建合件 的本地化字符串。
        /// </summary>
        public static string CompositePiecesSet {
            get {
                return ResourceManager.GetString("CompositePiecesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确认删除此角色信息？ 的本地化字符串。
        /// </summary>
        public static string ConfirmDeleteRole {
            get {
                return ResourceManager.GetString("ConfirmDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据信息转换实体类失败 的本地化字符串。
        /// </summary>
        public static string ConvertDtoFail {
            get {
                return ResourceManager.GetString("ConvertDtoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换失败 的本地化字符串。
        /// </summary>
        public static string ConvertFail {
            get {
                return ResourceManager.GetString("ConvertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;strong&gt;Copyright &amp;copy; 2017 &lt;a href=&quot;javascript:;&quot;&gt;OpenInfo Studio&lt;/a&gt;.&lt;/strong&gt; All rights reserved. 的本地化字符串。
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前三表日期 的本地化字符串。
        /// </summary>
        public static string CurrentTableDate3 {
            get {
                return ResourceManager.GetString("CurrentTableDate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前三表版本 的本地化字符串。
        /// </summary>
        public static string CurrentTableVersion3 {
            get {
                return ResourceManager.GetString("CurrentTableVersion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认列表 的本地化字符串。
        /// </summary>
        public static string DefaultList {
            get {
                return ResourceManager.GetString("DefaultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除角色信息成功 的本地化字符串。
        /// </summary>
        public static string DeleteRoleInfoSuccess {
            get {
                return ResourceManager.GetString("DeleteRoleInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设计变更 的本地化字符串。
        /// </summary>
        public static string DesignChange {
            get {
                return ResourceManager.GetString("DesignChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限分配 的本地化字符串。
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有任何权限 的本地化字符串。
        /// </summary>
        public static string DoNotHaveAnyRights {
            get {
                return ResourceManager.GetString("DoNotHaveAnyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑角色信息 的本地化字符串。
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑角色信息成功 的本地化字符串。
        /// </summary>
        public static string EditRoleInfoSuccess {
            get {
                return ResourceManager.GetString("EditRoleInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑角色权限成功 的本地化字符串。
        /// </summary>
        public static string EditRoleRightSuccess {
            get {
                return ResourceManager.GetString("EditRoleRightSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户信息 的本地化字符串。
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户角色信息成功 的本地化字符串。
        /// </summary>
        public static string EditUserRoleSuccess {
            get {
                return ResourceManager.GetString("EditUserRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用/停用 的本地化字符串。
        /// </summary>
        public static string EnableDisable {
            get {
                return ResourceManager.GetString("EnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找 的本地化字符串。
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找所有 的本地化字符串。
        /// </summary>
        public static string FindAll {
            get {
                return ResourceManager.GetString("FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找所有件 的本地化字符串。
        /// </summary>
        public static string FindOthers {
            get {
                return ResourceManager.GetString("FindOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加域 的本地化字符串。
        /// </summary>
        public static string GroupAdd {
            get {
                return ResourceManager.GetString("GroupAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加域用户 的本地化字符串。
        /// </summary>
        public static string GroupAddUsers {
            get {
                return ResourceManager.GetString("GroupAddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从域中删除用户 的本地化字符串。
        /// </summary>
        public static string GroupDeleteUsers {
            get {
                return ResourceManager.GetString("GroupDeleteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改域名称 的本地化字符串。
        /// </summary>
        public static string GroupEdit {
            get {
                return ResourceManager.GetString("GroupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域管理页面 的本地化字符串。
        /// </summary>
        public static string GroupIndex {
            get {
                return ResourceManager.GetString("GroupIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新域 的本地化字符串。
        /// </summary>
        public static string GroupRefresh {
            get {
                return ResourceManager.GetString("GroupRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新域成员 的本地化字符串。
        /// </summary>
        public static string GroupRefreshUsers {
            get {
                return ResourceManager.GetString("GroupRefreshUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除域 的本地化字符串。
        /// </summary>
        public static string GroupRemove {
            get {
                return ResourceManager.GetString("GroupRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制面板 的本地化字符串。
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码不正确 的本地化字符串。
        /// </summary>
        public static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整性核查 的本地化字符串。
        /// </summary>
        public static string IntegrityCheck {
            get {
                return ResourceManager.GetString("IntegrityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整性核查状态 的本地化字符串。
        /// </summary>
        public static string IntegrityCheckedStatus {
            get {
                return ResourceManager.GetString("IntegrityCheckedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前产品完整性核查状态 的本地化字符串。
        /// </summary>
        public static string IntegrityCheckStatus {
            get {
                return ResourceManager.GetString("IntegrityCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否已完成完整性核查 的本地化字符串。
        /// </summary>
        public static string IsIntegrityChecked {
            get {
                return ResourceManager.GetString("IsIntegrityChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否已完成销售件设置 的本地化字符串。
        /// </summary>
        public static string IsSaleSet {
            get {
                return ResourceManager.GetString("IsSaleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新物料 的本地化字符串。
        /// </summary>
        public static string ItemAdd {
            get {
                return ResourceManager.GetString("ItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料BOM详情 的本地化字符串。
        /// </summary>
        public static string ItemBomDetail {
            get {
                return ResourceManager.GetString("ItemBomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扣料设置 的本地化字符串。
        /// </summary>
        public static string ItemBuckleSet {
            get {
                return ResourceManager.GetString("ItemBuckleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动扣料 的本地化字符串。
        /// </summary>
        public static string ItemBuckleStart {
            get {
                return ResourceManager.GetString("ItemBuckleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM合件 的本地化字符串。
        /// </summary>
        public static string ItemCombine {
            get {
                return ResourceManager.GetString("ItemCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除物料 的本地化字符串。
        /// </summary>
        public static string ItemDelete {
            get {
                return ResourceManager.GetString("ItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改物料信息 的本地化字符串。
        /// </summary>
        public static string ItemEdit {
            get {
                return ResourceManager.GetString("ItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改物料数量 的本地化字符串。
        /// </summary>
        public static string ItemEditQuantity {
            get {
                return ResourceManager.GetString("ItemEditQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料分类标识设置 的本地化字符串。
        /// </summary>
        public static string ItemHlinkSetIndex {
            get {
                return ResourceManager.GetString("ItemHlinkSetIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用物料 的本地化字符串。
        /// </summary>
        public static string ItemLink {
            get {
                return ResourceManager.GetString("ItemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料名称 的本地化字符串。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料操作 的本地化字符串。
        /// </summary>
        public static string ItemOperation {
            get {
                return ResourceManager.GetString("ItemOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购件 的本地化字符串。
        /// </summary>
        public static string ItemPurchase {
            get {
                return ResourceManager.GetString("ItemPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售件 的本地化字符串。
        /// </summary>
        public static string ItemSale {
            get {
                return ResourceManager.GetString("ItemSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自制件 的本地化字符串。
        /// </summary>
        public static string ItemSelfmade {
            get {
                return ResourceManager.GetString("ItemSelfmade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除引用物料 的本地化字符串。
        /// </summary>
        public static string ItemUnlink {
            get {
                return ResourceManager.GetString("ItemUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM虚件 的本地化字符串。
        /// </summary>
        public static string ItemVirtual {
            get {
                return ResourceManager.GetString("ItemVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字 的本地化字符串。
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理菜单 的本地化字符串。
        /// </summary>
        public static string LeftSidebar {
            get {
                return ResourceManager.GetString("LeftSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;Admin&lt;/b&gt;LTE 的本地化字符串。
        /// </summary>
        public static string LogoLarge {
            get {
                return ResourceManager.GetString("LogoLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;A&lt;/b&gt;LT 的本地化字符串。
        /// </summary>
        public static string LogoMini {
            get {
                return ResourceManager.GetString("LogoMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM发布维护 的本地化字符串。
        /// </summary>
        public static string MaintenanceIndex {
            get {
                return ResourceManager.GetString("MaintenanceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM变更维护 的本地化字符串。
        /// </summary>
        public static string MBOMChangeMaintenance {
            get {
                return ResourceManager.GetString("MBOMChangeMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM版本创建修改 的本地化字符串。
        /// </summary>
        public static string MBOMCreatePublish {
            get {
                return ResourceManager.GetString("MBOMCreatePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM维护 的本地化字符串。
        /// </summary>
        public static string MBOMIndex {
            get {
                return ResourceManager.GetString("MBOMIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM列表 的本地化字符串。
        /// </summary>
        public static string MBOMList {
            get {
                return ResourceManager.GetString("MBOMList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM产品变更维护 的本地化字符串。
        /// </summary>
        public static string MBOMProductChangeIndex {
            get {
                return ResourceManager.GetString("MBOMProductChangeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM发布 的本地化字符串。
        /// </summary>
        public static string MBOMPublish {
            get {
                return ResourceManager.GetString("MBOMPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MBOM发布维护 的本地化字符串。
        /// </summary>
        public static string MBOMPublishMaintenance {
            get {
                return ResourceManager.GetString("MBOMPublishMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单树 的本地化字符串。
        /// </summary>
        public static string MenuTree {
            get {
                return ResourceManager.GetString("MenuTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 至少为 {1} 位长度 的本地化字符串。
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块描述 的本地化字符串。
        /// </summary>
        public static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建角色 的本地化字符串。
        /// </summary>
        public static string NewRole {
            get {
                return ResourceManager.GetString("NewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建用户 的本地化字符串。
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户尚未登录 的本地化字符串。
        /// </summary>
        public static string NotLogin {
            get {
                return ResourceManager.GetString("NotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加选装件 的本地化字符串。
        /// </summary>
        public static string OptionalItemsAdd {
            get {
                return ResourceManager.GetString("OptionalItemsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品选装关系设置 的本地化字符串。
        /// </summary>
        public static string OptionalItemsIndex {
            get {
                return ResourceManager.GetString("OptionalItemsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织架构树 的本地化字符串。
        /// </summary>
        public static string OrganizationTree {
            get {
                return ResourceManager.GetString("OrganizationTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数为空 的本地化字符串。
        /// </summary>
        public static string ParamIsEmpty {
            get {
                return ResourceManager.GetString("ParamIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PBOM变更（部件） 的本地化字符串。
        /// </summary>
        public static string PBomChangeItemIndex {
            get {
                return ResourceManager.GetString("PBomChangeItemIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PBOM变更（产品） 的本地化字符串。
        /// </summary>
        public static string PBomChangeProdIndex {
            get {
                return ResourceManager.GetString("PBomChangeProdIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺BOM 的本地化字符串。
        /// </summary>
        public static string PBOMList {
            get {
                return ResourceManager.GetString("PBOMList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序流程清单 的本地化字符串。
        /// </summary>
        public static string ProcessFlowList {
            get {
                return ResourceManager.GetString("ProcessFlowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核查状态 的本地化字符串。
        /// </summary>
        public static string ProductCheckStatus {
            get {
                return ResourceManager.GetString("ProductCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编码 的本地化字符串。
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品详情 的本地化字符串。
        /// </summary>
        public static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品MBOM详情 的本地化字符串。
        /// </summary>
        public static string ProductMBomDetail {
            get {
                return ResourceManager.GetString("ProductMBomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品PBOM详情 的本地化字符串。
        /// </summary>
        public static string ProductPBomDetail {
            get {
                return ResourceManager.GetString("ProductPBomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品发布维护 的本地化字符串。
        /// </summary>
        public static string ProductReleaseMaintenance {
            get {
                return ResourceManager.GetString("ProductReleaseMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string ProductStatus {
            get {
                return ResourceManager.GetString("ProductStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人资料 的本地化字符串。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目编号 的本地化字符串。
        /// </summary>
        public static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名称 的本地化字符串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目发布 的本地化字符串。
        /// </summary>
        public static string ProjectPublish {
            get {
                return ResourceManager.GetString("ProjectPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购件清单 的本地化字符串。
        /// </summary>
        public static string PurchaseList {
            get {
                return ResourceManager.GetString("PurchaseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新MBOM数据 的本地化字符串。
        /// </summary>
        public static string RefreshMbom {
            get {
                return ResourceManager.GetString("RefreshMbom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销更改 的本地化字符串。
        /// </summary>
        public static string RejectChanges {
            get {
                return ResourceManager.GetString("RejectChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新加载表格 的本地化字符串。
        /// </summary>
        public static string ReloadTable {
            get {
                return ResourceManager.GetString("ReloadTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我 的本地化字符串。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除操作权限 的本地化字符串。
        /// </summary>
        public static string RemoveAction {
            get {
                return ResourceManager.GetString("RemoveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除角色 的本地化字符串。
        /// </summary>
        public static string RemoveRole {
            get {
                return ResourceManager.GetString("RemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户 的本地化字符串。
        /// </summary>
        public static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能为空 的本地化字符串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色描述 的本地化字符串。
        /// </summary>
        public static string RoleDescription {
            get {
                return ResourceManager.GetString("RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色信息 的本地化字符串。
        /// </summary>
        public static string RoleInformation {
            get {
                return ResourceManager.GetString("RoleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色不存在 的本地化字符串。
        /// </summary>
        public static string RoleNotExist {
            get {
                return ResourceManager.GetString("RoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色权限 的本地化字符串。
        /// </summary>
        public static string RoleRights {
            get {
                return ResourceManager.GetString("RoleRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售件设置 的本地化字符串。
        /// </summary>
        public static string SaleSet {
            get {
                return ResourceManager.GetString("SaleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并提交 的本地化字符串。
        /// </summary>
        public static string SaveAndSubmit {
            get {
                return ResourceManager.GetString("SaveAndSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自制件清单 的本地化字符串。
        /// </summary>
        public static string SelfMadeList {
            get {
                return ResourceManager.GetString("SelfMadeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售件清单 的本地化字符串。
        /// </summary>
        public static string SellList {
            get {
                return ResourceManager.GetString("SellList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置为零部件 的本地化字符串。
        /// </summary>
        public static string SetItems {
            get {
                return ResourceManager.GetString("SetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置为销售件 的本地化字符串。
        /// </summary>
        public static string SetSaleItems {
            get {
                return ResourceManager.GetString("SetSaleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示物料流程信息 的本地化字符串。
        /// </summary>
        public static string ShowItemProcessInfo {
            get {
                return ResourceManager.GetString("ShowItemProcessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登出 的本地化字符串。
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准件清单 的本地化字符串。
        /// </summary>
        public static string StandardList {
            get {
                return ResourceManager.GetString("StandardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三表设计者 的本地化字符串。
        /// </summary>
        public static string TableDesigner3 {
            get {
                return ResourceManager.GetString("TableDesigner3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格操作 的本地化字符串。
        /// </summary>
        public static string TableOperation {
            get {
                return ResourceManager.GetString("TableOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码 的本地化字符串。
        /// </summary>
        public static string TEL {
            get {
                return ResourceManager.GetString("TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击行时切换选中状态 的本地化字符串。
        /// </summary>
        public static string ToggleCheckStateOnSelect {
            get {
                return ResourceManager.GetString("ToggleCheckStateOnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转批发起 的本地化字符串。
        /// </summary>
        public static string TransferInitiate {
            get {
                return ResourceManager.GetString("TransferInitiate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;Version&lt;/b&gt; 0.0.1 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看角色用户 的本地化字符串。
        /// </summary>
        public static string ViewRoleUsers {
            get {
                return ResourceManager.GetString("ViewRoleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消虚件标识 的本地化字符串。
        /// </summary>
        public static string VirtualPiecesCancel {
            get {
                return ResourceManager.GetString("VirtualPiecesCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚件操作 的本地化字符串。
        /// </summary>
        public static string VirtualPiecesOperation {
            get {
                return ResourceManager.GetString("VirtualPiecesOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除虚件引用 的本地化字符串。
        /// </summary>
        public static string VirtualPiecesQuoteCancel {
            get {
                return ResourceManager.GetString("VirtualPiecesQuoteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用虚件下级 的本地化字符串。
        /// </summary>
        public static string VirtualPiecesQuoteSet {
            get {
                return ResourceManager.GetString("VirtualPiecesQuoteSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为虚件 的本地化字符串。
        /// </summary>
        public static string VirtualPiecesSet {
            get {
                return ResourceManager.GetString("VirtualPiecesSet", resourceCulture);
            }
        }
    }
}
