var lang = {
    alertTitle: "警告",
    infoTitle: "提示",
    progressTitle: "页面载入中",
    loading: "加载中，请稍后……",
    projectCode: "项目编号",
    projectName: "项目名称",
    productCode: "产品编号",
    productName: "产品名称",
    pbomVer: "PBOM版本",
    mbomVer: "MBOM版本",
    status: "状态",
    remarks: "备注",
    menu:{
        name: "菜单名称",
        iconcls: "图标",
        order: "排序",
        url: "链接",
        desc:"说明"
    },
    item:{
        code: "代号",
        name: "名称",
        itemcode: "物料编码",
        displayname: "显示名称",
        gg: "规格",
        xh: "型号",
        desc: "备注信息",
        weight: "重量",
        unit: "单位",
        type: "类型",
        istoerp: "是否发布",
        status: "状态",
        expiryerp: "过期日期",
        create: "创建日期",
        createby: "创建用户ID",
        createlogin: "创建用户",
        createname: "创建人"
    },
    cp: {
        bywhat: "实施依据",
        source: "物料来源",
        changesign: "变更标志",
        impactdo: "是否已实施",
        paraitemcode: "对应物料编号",
        paraname: "对应物料名称",
    },
    oitem:{
        code: "选装件编码",
        name: "选装件名称",
        itemcode: "选装件物料编码"
    },
    role: {
        notSelectUsers:"未选中任何用户"
    },
    transfer: {
        initiateSuccess:"转批成功",
        initiateFailed:"转批发起失败，请联系管理员"
    },
    maintenance: {
        baseInfo: "基本信息",
        saleSet: "销售件设置",
        integrityCheck: "完整性核查",
        pbom: "PBOM",
        mbom: "MBOM",
        bomtree: "BOM反查",
        bomList: "物料清单",
        selfMadeList: "自制件清单",
        standardList: "标准件清单",
        purchaseList: "采购件清单",
        itemList: "零部件清单",
        sellList: "销售件清单",
        processFlowList: "工序流程清单"
    },
    saleSet: {
        shippingAddr: "发运地点",
        customerName: "客户名称",
        customerItemCode: "客户物料号",
        customerItemName: "客户物料名称",
        saleSet: "销售件设置",
        integrityCheck: "完整性设置",
        productCode: "零件号",
        productName: "零件名称",
        productUnit: "单位",
        saleWeight: "销售重量",
        notValid: "请检查是否已经填写所有的销售件信息",
        noChanges: "没有检查到任何修改，无需保存",
        saleSetSuccess: "销售件设置成功",
        saleSetFailed: "销售件设置失败，请检查填写信息是否有误或联系管理员"
    },
    bomlist: {
        dataGetFailed: "数据获取失败，请重试或联系管理员",
        child: "部件",
        selfmade: "自制件",
        standard: "标准件",
        purchase: "采购件",
        sell: "销售件",
        process: "工艺件",
        origin: "原材料",
        pack: "包装件",
        borrow: "借用"
    },
    selfmade: {
        code:"零件代号",
        itemcode:"物料编码",
        name:"名称",
        date:"发布日期",
        borrow: "借用",
        remarks: "备注"
    },
    processFlow: {
        loadFailed:"加载列表失败，请联系管理员",
        itemList: "零件列表",
        processInfo:"流程信息",
        gxCode: "工序编号",
        gxName: "工序名称",
        gxnr: "说明"
    },
    pbom: {
        name: "产品名称",
        prodcode: "产品编码",
        itemcode: "物料编码",
        itemname: "物料名称",
        baseprod: "三表所在直接产品",
        desc: "备注",
        ver: "PBOM版本",
        dtver: "PBOM版本日期",
        effect: "影响面",
        displayname: "子项",
        quantity: "产品数量",
        status: "PBOM变更类型",
        isimplement: "MBOM是否已实施",
        notice: "MBOM实施依据",
        dttoerp: "ERP日期",
        createname: "创建人"
    },
    mbom: {
        noSelectRoot: "禁止选择根节点",
        noMultiSelect: "选择了多个项，此操作不可多选",
        notSelect: "未选择任何项",
        notSelectMain: "未选择主表项",
        notSelectDiscrete: "未选择离散区列表中的任何项",
        notSelectSingleDiscrete: "选择了多个处于【离散区】的项，仅可选中一个",
        notSelectSame: "在【主选区】选择的件和【离散区】选择的件是同一个件",
        notSelectSameParent: "选择的多个件并不属于同一父项下",
        notSelectSameVirtual: "选择的多个虚件并非同属一个父级",
        notSelectVirtualRoot: "选择的虚件非虚件根级",
        notChild: "选中的【离散区子项】不属于选择项的【子级】",
        notSelectHaveType: "选中的项已经为虚件或合件，无法重复设置",
        notSelectComposite: "选择的项非合件，请选择合件项",
        notSelectDiscreteComposite: "在【离散列表】所选择的项非【合件】",
        notSelectVirtual: "选择的项非虚件，请选择虚件项",
        notSelectDiscreteVirtual: "在【离散列表】所选择的项非【虚件】",
        isDeducted: "选择项中有已经设置扣料信息的",
        notHaveProcessInfo: "选中件父级不包含工序流程信息，请联系管理员",
        titleDiscreteList: "离散区列表",
        getItemFailed: "获取选择项信息失败",
        haveToSelectParent: "必须选择拥有子级的项",
        itemDeductionSetSuccess: "设置扣料成功",
        refreshCooldown: "刷新过于频繁，请稍后",
        beginDeduction: "启动扣料",
        endDeduction: "关闭扣料",
        maintenance:"MBOM维护",
        changemaintenance: "MBOM变更维护",
        maintenanceStatus: "维护状态",
        checkStatus: "核查状态",
        techStatus: "技术状态",
        order: "BOM序号",
        itemCode: "物料号",
        itemName: "物料名称",
        editCombineName: "修改合件名称",
        inputNewCombineName: "请输入新的合件名称",
        quantity: "数量",
        process: "扣料工序",
        level:"层级",
        unit: "单位",
        kl:"扣料信息"
    }
};
