ALTER PROCEDURE PROC_MBOM_PROCESS_SET
(
@GUID_VER UNIQUEIDENTIFIER,
@GUID_MBOM UNIQUEIDENTIFIER,
@GUID_PROCESS VARCHAR(48),
@TYPE INT,
@USERID INT,
@NAME VARCHAR(32),
@LOGIN VARCHAR(32)
)
AS
BEGIN
	--
	DECLARE @MSG VARCHAR(200) = '设置成功！'
	DECLARE @SUCCESS BIT = 1
	DECLARE @DATE DATETIME = GETDATE()
	--先删除之前的数据
	IF @TYPE < 2
	BEGIN
		DELETE FROM TN_80_APP_1050_PRODUCTION_LINE_PROCESS_VER_HLINK
		WHERE CN_GUID_VER = @GUID_VER AND CN_GUID_MBOM = @GUID_MBOM
	END

	DECLARE @IS_A BIT,@IS_B BIT,@IS_C BIT
	SET @IS_A = CASE @TYPE WHEN 0 THEN 1 ELSE 0 END
	SET @IS_B = CASE @TYPE WHEN 1 THEN 1 ELSE 0 END
	SET @IS_C = CASE @TYPE WHEN 2 THEN 1 ELSE 0 END
	--添加新数据
	INSERT INTO [dbo].[TN_80_APP_1050_PRODUCTION_LINE_PROCESS_VER_HLINK]
		([CN_GUID_VER]
		,[CN_GUID_MBOM]
		,[CN_GUID_PROCESS]
		,[CN_IS_ASSEMBLED]
		,[CN_IS_FEEDED]
		,[CN_IS_EMPTY]
		,[CN_DT_CREATE]
		,[CN_DT_EFFECTIVE]
		,[CN_DT_EXPIRY]
		,[CN_CREATE_BY]
		,[CN_CREATE_NAME]
		,[CN_CREATE_LOGIN]) 
	SELECT
		 @GUID_VER
		,@GUID_MBOM
		,CASE WHEN LEN(@GUID_PROCESS) = 0 THEN NULL ELSE CAST(@GUID_PROCESS AS UNIQUEIDENTIFIER) END
		,@IS_A
		,@IS_B
		,@IS_C
		,@DATE
		,@DATE
		,'2100-01-01'
		,@USERID
		,@NAME
		,@LOGIN
	--
	SELECT @MSG AS MSG, @SUCCESS AS SUCCESS
END;
GO