ALTER PROCEDURE PROC_GET_ITEM_PARENTS
(
@ITEMCODE VARCHAR(32)
)
AS
BEGIN
	DECLARE @DATE DATETIME = GETDATE()

	SELECT 
	ITEM.CN_ITEM_CODE AS ITEMCODE,
	ITEM.CN_NAME AS NAME
	FROM TN_80_APP_0040_MBOM_HLINK AS MBOM
	INNER JOIN TN_80_APP_0000_ITEM AS ITEM ON ITEM.CN_ITEM_CODE = MBOM.CN_ITEMCODE_PARENT 
	WHERE MBOM.CN_ITEMCODE = @ITEMCODE
	AND MBOM.CN_DT_EFFECTIVE < @DATE
	AND MBOM.CN_DT_EXPIRY > @DATE
END;
GO