ALTER PROCEDURE PROC_PRODUCT_VER_CREATE
(
	@PROD_ITEMCODE VARCHAR(32),
	@vername VARCHAR(32),
	@desc VARCHAR(32),
	@userid INT,
	@name VARCHAR(32),
	@login VARCHAR(32)
)
AS
BEGIN
	DECLARE @ERROR INT = 0
	DECLARE @MSG VARCHAR(200)
	DECLARE @SUCCESS BIT = 1
	
	BEGIN TRAN
	-- 将以前版本的状态修改为''
	UPDATE [TN_80_APP_0010_PRODUCT_VER]
	SET CN_STATUS = ''
	WHERE CN_PRODUCT_ITEMCODE = @PROD_ITEMCODE
	AND CN_STATUS = 'Y'

	-- 创建新版本
	INSERT INTO [dbo].[TN_80_APP_0010_PRODUCT_VER]
		([CN_GUID]
		,[CN_PRODUCT_CODE]
		,[CN_PRODUCT_ITEMCODE]
		,[CN_PRODUCT_NAME]
		,[CN_NAME]
		,[CN_DESC]
		,[CN_STATUS]
		,[CN_DT_CREATE]
		,[CN_CREATE_BY]
		,[CN_CREATE_NAME]
		,[CN_CREATE_LOGIN])
	SELECT
		 NEWID()
		,CN_CODE
		,CN_ITEM_CODE
		,CN_NAME
		,@vername
		,@desc
		,'Y'
		,GETDATE()
		,@userid
		,@name
		,@login
	FROM TN_80_APP_0000_ITEM
	WHERE CN_ITEM_CODE = @PROD_ITEMCODE
	SET @ERROR = @ERROR + @@ERROR

	IF @ERROR > 0
	BEGIN
		SET @MSG = '创建版本失败，请联系管理员'
		RAISERROR(@MSG, 15, 1)
		ROLLBACK
		RETURN
	END
	ELSE
	BEGIN
		SET @MSG = '已成功创建版本'
		COMMIT TRAN
	END

	SELECT @MSG AS MSG, @SUCCESS AS SUCCESS
END