ALTER PROCEDURE PROC_GET_ITEM_TREE
(
@ITEMCODE VARCHAR(32)
)
AS
BEGIN
	DECLARE @DATE DATETIME = GETDATE();
	-- 根节点
	SELECT 
		0 AS [LEVEL]
		,CAST(NULL AS VARCHAR) AS PARENTID
		,CAST('P' AS VARCHAR) AS ID
		,ITEM.CN_ID AS ITEMID
		,RTRIM(ITEM.CN_NAME) AS NAME
		,RTRIM(ITEM.CN_CODE) AS CODE
		,RTRIM(ITEM.CN_ITEM_CODE) AS ITEMCODE
		,CAST(NULL AS UNIQUEIDENTIFIER) AS [GUID]
		,1 AS QUANTITY
		,'件' AS UNIT
		,CAST(0 AS BIT) AS ISBORROW
		,0 AS [ISTOERP]
		,0 AS [ISMBOM]
		,0 AS [ORDER]
		,'' AS [TYPE]
		,'Y' AS [STATUS]
	FROM TN_80_APP_0000_ITEM AS ITEM
	WHERE ITEM.CN_ITEM_CODE = @ITEMCODE 
	-- 除根节点外所有子节点
	UNION ALL
	SELECT
		1 AS CN_LEVEL
		,CAST('P' AS VARCHAR(200)) AS CN_PARENTID
		,CAST('P'+ SUBSTRING(CAST(MBOMHLINK.CN_GUID AS CHAR(36)),1,5) AS VARCHAR(200)) AS CN_ID
		,ITEM.CN_ID AS CN_ITEMID
		,RTRIM(ITEM.CN_NAME) AS CN_NAME
		,RTRIM(ITEM.CN_CODE) AS CN_CODE
		,RTRIM(ITEM.CN_ITEM_CODE) AS CN_ITEMCODE
		,MBOMHLINK.CN_GUID
		,MBOMHLINK.CN_QUANTITY
		,MBOMHLINK.CN_UNIT
		,MBOMHLINK.CN_ISBORROW
		,MBOMHLINK.CN_IS_TOERP
		,MBOMHLINK.CN_ISMBOM
		,MBOMHLINK.CN_ORDER 
		,'' AS [TYPE]
		,'Y' AS [STATUS]
	FROM TN_80_APP_0040_MBOM_HLINK AS MBOMHLINK 
	INNER JOIN TN_80_APP_0000_ITEM AS ITEM ON ITEM.CN_ITEM_CODE = MBOMHLINK.CN_ITEMCODE
	WHERE MBOMHLINK.CN_ITEMCODE_PARENT = @ITEMCODE
	AND MBOMHLINK.CN_DT_EFFECTIVE_PBOM < @DATE
	AND MBOMHLINK.CN_DT_EXPIRY_PBOM > @DATE
	AND MBOMHLINK.CN_DT_EFFECTIVE < @DATE
	AND MBOMHLINK.CN_DT_EXPIRY > @DATE
	ORDER BY [ORDER]
END;
GO
EXEC PROC_GET_ITEM_TREE 'HGS7A2168100P1'