CREATE PROCEDURE PROC_GET_PRODUCT_MBOM_VER_LIST
(
@PROD_ITEMCODE VARCHAR(32)
)
AS
BEGIN
	
	IF EXISTS ( SELECT 1 FROM 
	TN_80_APP_0040_MBOM_VER
	WHERE CN_ITEM_CODE = @PROD_ITEMCODE )
	BEGIN
		SELECT 
			CN_VER AS VER,
			CONVERT(CHAR(10),CN_DT_CREATE,20) AS DATETIMECREATE,
			CN_DESC AS [DESC]
		FROM
		TN_80_APP_0040_MBOM_VER
		WHERE CN_ITEM_CODE = @PROD_ITEMCODE
	END
	ELSE
	BEGIN
		SELECT 
			'无版本' AS VER,
			CONVERT(CHAR(10),GETDATE(),20) AS DATETIMECREATE,
			'按当前时间展示' AS [DESC]
	END
END;
GO