CREATE PROCEDURE PROC_PRODUCT_TRANSFER_PUBLISH
(
@PROD_ITEMCODE VARCHAR(32),
@USERID INT,
@NAME VARCHAR(32),
@LOGIN VARCHAR(32)
)
AS
BEGIN
	DECLARE @MSG VARCHAR(200) = '销售件版本发布成功'
	DECLARE @SUCCESS BIT = 1
	DECLARE @DATE DATETIME = GETDATE()
	DECLARE @GUID_PRODVER UNIQUEIDENTIFIER = DBO.GETPRODUCTVER(@PROD_ITEMCODE);

	IF @GUID_PRODVER IS NULL
	BEGIN
		SET @MSG = '无销售件版本。'
		SET @SUCCESS = 0
		SELECT @MSG AS MSG, @SUCCESS AS SUCCESS
		RETURN
	END

	IF NOT EXISTS ( SELECT 1 FROM TN_80_APP_0010_PRODUCT_VER WHERE CN_GUID = @GUID_PRODVER AND CN_IS_TOERP = 0 )
	BEGIN
		SET @MSG = '销售件版本已经发布，无需再次发布。'
		SET @SUCCESS = 0
		SELECT @MSG AS MSG, @SUCCESS AS SUCCESS
		RETURN
	END
	
	UPDATE TN_80_APP_0010_PRODUCT_VER
	SET 
		 CN_IS_TOERP = 1
		,CN_DT_TOERP = @DATE
	WHERE CN_GUID = @GUID_PRODVER

	SELECT @MSG AS MSG, @SUCCESS AS SUCCESS
END;
GO
