CREATE TABLE [dbo].[TN_50_DIC_0005_PRODUCT_LINE](
	[CN_ID] [int] IDENTITY(1,1) NOT NULL,
	[CN_CODE] [varchar](32) NOT NULL,
	[CN_NUMBER] [int] NOT NULL,
	[CN_NAME] [varchar](32) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ON 
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (26, N'BSC', 2100, N'变速器手动换挡拨叉')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (27, N'BSD', 2300, N'CVT传送带')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (28, N'DXQ', 1310, N'涨簧式高调器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (29, N'GTB', 1330, N'滑靴式高调器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (30, N'GTJ', 1500, N'汽车座椅其他类调节机构')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (31, N'HGS', 1210, N'直线钢珠轴承式滑轨')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (32, N'QYG', 3000, N'汽车座椅骨架')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (33, N'TJB', 1110, N'有级调角器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (34, N'TJJ', 1500, N'汽车座椅其他类调节机构')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (35, N'TJL', 1120, N'无级调角器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (36, N'TJW', 1120, N'无级调角器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (37, N'TJX', 1120, N'无级调角器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (38, N'TJZ', 1500, N'汽车座椅其他类调节机构')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (39, N'U', 400, N'包装材料')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (40, N'XWQ', 1400, N'汽车座椅折叠器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (41, N'ZZZ', 1340, N'电动高调器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (42, N'ZZZ', 1350, N'其他类高调器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (43, N'ZZZ', 2200, N'变速箱离合器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (44, N'ZZZ', 1130, N'有级无级混合配置')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (45, N'ZZZ', 1140, N'其他类调角器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (46, N'ZZZ', 1220, N'其他类滑轨')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (47, N'ZZZ', 1320, N'滚柱式高调器')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (48, N'ZZZ', 4000, N'精冲产品')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (49, N'ZZZ', 5000, N'其他类产品')
GO
INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] ([CN_ID], [CN_CODE], [CN_NUMBER], [CN_NAME]) VALUES (50, N'ZZZ', 2500, N'其他动力系产品')
GO
SET IDENTITY_INSERT [dbo].[TN_50_DIC_0005_PRODUCT_LINE] OFF
GO


