CREATE TABLE TN_50_DIC_0010_STATUS
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()), -- 唯一标识
	CN_TYPE VARCHAR(32) NOT NULL,						-- 类别，如：PRODUCT、PROJECT、ITEM，不同分类使用状态不一样
	CN_NAME VARCHAR(32) NOT NULL,						-- 状态名称
	CN_DESC VARCHAR(256),								-- 状态说明
	CN_ORDER INT NOT NULL,								-- 状态排序
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),	-- -------
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),-- -------
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),	-- -------
	CN_CREATE_BY INT NOT NULL,							-- -------
	CN_CREATE_NAME VARCHAR(32) NOT NULL,				-- -------
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL				-- -------
)
GO
INSERT INTO TN_50_DIC_0010_STATUS
(
CN_ORDER,
CN_TYPE,
CN_NAME,
CN_CREATE_BY,
CN_CREATE_NAME,
CN_CREATE_LOGIN
)
SELECT 1000,'PRODUCT','待发起预转批',0,'超级管理员','admin' UNION
SELECT 2000,'PRODUCT','销售件已设置',0,'超级管理员','admin' UNION
SELECT 3000,'PRODUCT','MBOM维护中',0,'超级管理员','admin' UNION
SELECT 4000,'PRODUCT','MBOM发布中',0,'超级管理员','admin' UNION
SELECT 5000,'PRODUCT','MBOM发布完成',0,'超级管理员','admin' UNION
SELECT 6000,'PRODUCT','转批中',0,'超级管理员','admin' UNION
SELECT 7000,'PRODUCT','已转批',0,'超级管理员','admin'
GO 
SELECT * FROM TN_50_DIC_0010_STATUS 