-- 工序生产线
CREATE TABLE TN_80_APP_1050_PRODUCTION_LINE
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	CN_LINE_CODE VARCHAR(32) NOT NULL UNIQUE,	-- 生产线编码，HG_XXXX
	CN_LINE_NAME VARCHAR(32) NOT NULL UNIQUE,	-- 生产线名称，1号滑道生产线
	CN_LINE_INFO VARCHAR(256) NOT NULL, -- 生产线说明
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)

INSERT INTO TN_80_APP_1050_PRODUCTION_LINE
(
	 CN_LINE_CODE
	,CN_LINE_NAME
	,CN_LINE_INFO
	,CN_CREATE_BY
	,CN_CREATE_NAME
	,CN_CREATE_LOGIN
)
SELECT 'TEST_LINE_0001','测试生产线0001','用于生产HGS、HG系列产品',0,'超级管理员','超级管理员' UNION
SELECT 'TEST_LINE_0002','测试生产线0002','用于生产LGT、ZZZ、TCL系列产品',0,'超级管理员','超级管理员'

-- 工序生产线对应可生产产品
CREATE TABLE TN_80_APP_1050_PRODUCTION_LINE_PRODUCT
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	CN_GUID_LINE UNIQUEIDENTIFIER NOT NULL,				-- 生产线GUID
	CN_PRODUCT_ITEMCODE VARCHAR(32) NOT NULL,			-- 生产线可生产产品
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)
INSERT INTO TN_80_APP_1050_PRODUCTION_LINE_PRODUCT
(
	 CN_GUID_LINE
	,CN_PRODUCT_ITEMCODE
	,CN_CREATE_BY
	,CN_CREATE_NAME
	,CN_CREATE_LOGIN
)
SELECT CN_GUID,'HGS6800100P1',0,'超级管理员','超级管理员' FROM TN_80_APP_1050_PRODUCTION_LINE
-- 工序生产线的产品工序信息
CREATE TABLE TN_80_APP_1050_PRODUCTION_LINE_PRODUCT_PROCESS
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	CN_GUID_LINE_PRODUCT UNIQUEIDENTIFIER NOT NULL,			--生产线产品GUID
	CN_PROCESS_ORDER VARCHAR(10) NOT NULL,					--工序编号，05序、10序……
	CN_PROCESS_NAME VARCHAR(32) NOT NULL,					--工序名称，切割、涂油、焊接……
	CN_PROCESS_INFO VARCHAR(256),
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)
-- 产品工序生产线版本  
CREATE TABLE TN_80_APP_1050_PRODUCTION_LINE_PROCESS_VER
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	CN_GUID_LINE_PRODUCT UNIQUEIDENTIFIER NOT NULL,				--生产线产品GUID，应用的是哪个生产线产品的工序
	CN_PRODUCT_ITEMCODE VARCHAR(32) NOT NULL,
	CN_NAME VARCHAR(32) NOT NULL,
	CN_DESC VARCHAR(256) NOT NULL,
	CN_IS_TOERP SMALLINT NOT NULL DEFAULT(0),
	CN_DT_TOERP DATETIME NOT NULL DEFAULT('2100-01-01'),
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
) 
-- 产品工序生产线版本详情表
CREATE TABLE TN_80_APP_1050_PRODUCTION_LINE_PROCESS_VER_HLINK
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID_VER UNIQUEIDENTIFIER NOT NULL,				--工序版本GUID
	CN_GUID_MBOM UNIQUEIDENTIFIER NOT NULL,				--MBOM对应物料的GUID
	CN_GUID_PROCESS UNIQUEIDENTIFIER,					--使用的工序的GUID
	CN_IS_ASSEMBLED BIT NOT NULL DEFAULT(0),			--是做成工序
	CN_IS_FEEDED BIT NOT NULL DEFAULT(0),				--是投料工序
	CN_IS_EMPTY BIT NOT NULL DEFAULT(0),				--是空工序
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)