-- 工序产品线
CREATE TABLE TN_80_APP_1050_PROCESS_LINE
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	CN_LINE_CODE VARCHAR(32) NOT NULL,	-- 产品线编码，HG_XXXX
	CN_LINE_NAME VARCHAR(32) NOT NULL,	-- 产品线名称，1号滑道产品线
	CN_LINE_INFO VARCHAR(256) NOT NULL, -- 产品线说明
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)
CREATE TABLE TN_80_APP_1050_PROCESS_LINE_HLINK
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID_LINE UNIQUEIDENTIFIER NOT NULL,				-- 产品线GUID
	CN_PRODUCT_ITEMCODE VARCHAR(32) NOT NULL,			-- 产品线可生产产品
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)
-- 工序产品线信息
CREATE TABLE TN_80_APP_1050_PROCESS_LINE_DETAIL
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID_LINE UNIQUEIDENTIFIER NOT NULL, --产品线GUID
	CN_PROCESS_ORDER VARCHAR(10) NOT NULL, --工序编号，05序、10序……
	CN_PROCESS_NAME VARCHAR(32) NOT NULL, --工序名称，切割、涂油、焊接……
	CN_PROCESS_INFO VARCHAR(256),
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)
-- 工序信息版本表
CREATE TABLE TN_80_APP_1050_PROCESS_VER
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	CN_PRODUCT_CODE VARCHAR(32) NOT NULL,
	CN_PRODUCT_ITEMCODE VARCHAR(32) NOT NULL,
	CN_NAME VARCHAR(32) NOT NULL,
	CN_DESC VARCHAR(256) NOT NULL,
	CN_IS_TOERP SMALLINT NOT NULL DEFAULT(0),
	CN_DT_TOERP DATETIME NOT NULL DEFAULT('2100-01-01'),
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)
-- 工序信息版本详情表
CREATE TABLE TN_80_APP_1050_PROCESS_VER_HLINK
(
	CN_ID INT IDENTITY(1,1) PRIMARY KEY,
	CN_GUID_VER UNIQUEIDENTIFIER NOT NULL, --工序版本GUID
	CN_GUID_LINE UNIQUEIDENTIFIER NOT NULL, --产品线GUID，应用的是哪个产品线的工序
	CN_PRODUCT_ITEMCODE VARCHAR(32) NOT NULL,
	CN_PROCESS_ORDER VARCHAR(10) NOT NULL, --工序编号，05序、10序……
	CN_PROCESS_NAME VARCHAR(32) NOT NULL, --工序名称，切割、涂油、焊接……
	CN_PROCESS_INFO VARCHAR(256),
	CN_ITEM_CODE VARCHAR(32) NOT NULL,
	CN_QUANTITY FLOAT NOT NULL,
	CN_DT_CREATE DATETIME NOT NULL DEFAULT(GETDATE()),
	CN_DT_EFFECTIVE DATE NOT NULL DEFAULT('2000-01-01'),
	CN_DT_EXPIRY DATE NOT NULL DEFAULT('2100-01-01'),
	CN_CREATE_BY INT NOT NULL,
	CN_CREATE_NAME VARCHAR(32) NOT NULL,
	CN_CREATE_LOGIN VARCHAR(32) NOT NULL
)

/*
使用流程：
=== 维护产品线信息 ===

填写【工序产品线】表
填写【工序产品线信息】表。

=== 对产品添加工序版本 ===

填写【工序信息版本】表
填写【工序信息版本详情】表，此处选择使用的产品线，将套用改产品线下产品线信息内容，然后用户将产品内的物料对应到工序中
*/