IF EXISTS ( SELECT * FROM SYSOBJECTS WHERE NAME = 'TRIG_UPDATE_PBOM2MBOM' )
BEGIN
	DROP TRIGGER TRIG_UPDATE_PBOM2MBOM
END
GO
CREATE TRIGGER TRIG_UPDATE_PBOM2MBOM
ON TN_80_APP_0030_PBOM_HLINK
AFTER UPDATE
AS
BEGIN
	UPDATE MBOMHLINK
	SET 
		 CN_ITEMCODE = PBOMHLINK.CN_ITEMCODE
		,CN_ITEMCODE_PARENT = PBOMHLINK.CN_ITEMCODE_PARENT
		,CN_DISPLAYNAME = PBOMHLINK.CN_DISPLAYNAME
		,CN_DT_EFFECTIVE_PBOM = PBOMHLINK.CN_DT_EFFECTIVE
		,CN_DT_EXPIRY_PBOM = PBOMHLINK.CN_DT_EXPIRY
		,CN_DT_TOERP = PBOMHLINK.CN_DT_TOERP
		,CN_IS_TOERP = PBOMHLINK.CN_IS_TOERP
		,CN_ISBORROW = PBOMHLINK.CN_ISBORROW
		,CN_QUANTITY = PBOMHLINK.CN_F_QUANTITY
		,CN_UNIT = PBOMHLINK.CN_UNIT
		,CN_ORDER = PBOMHLINK.CN_ORDER
	FROM TN_80_APP_0040_MBOM_HLINK AS MBOMHLINK
	INNER JOIN inserted AS PBOMHLINK ON PBOMHLINK.CN_GUID = MBOMHLINK.CN_GUID_PBOM
		AND MBOMHLINK.CN_ISMBOM = 0
END;
GO
IF EXISTS ( SELECT * FROM SYSOBJECTS WHERE NAME = 'TRIG_INSERT_PBOM2MBOM' )
BEGIN
	DROP TRIGGER TRIG_INSERT_PBOM2MBOM
END
GO
CREATE TRIGGER TRIG_INSERT_PBOM2MBOM
ON TN_80_APP_0030_PBOM_HLINK
AFTER INSERT
AS
BEGIN 
	INSERT INTO [dbo].[TN_80_APP_0040_MBOM_HLINK]
		(
	     [CN_GUID]
		,[CN_GUID_PBOM]
		,[CN_ITEMCODE_PARENT]
		,[CN_ITEMCODE]
		,[CN_QUANTITY]
		,[CN_DISPLAYNAME]
		,[CN_ORDER]
		,[CN_UNIT]
		,[CN_ISBORROW]
		,[CN_ISMBOM]
		,[CN_DT_CREATE]
		,[CN_DT_EFFECTIVE_PBOM]
		,[CN_DT_EXPIRY_PBOM]
		,[CN_DT_TOERP]
		,[CN_IS_TOERP]
		,[CN_DESC]
		,[CN_CREATE_BY]
		,[CN_CREATE_NAME]
		,[CN_CREATE_LOGIN])
	SELECT
		 NEWID()
		,CN_GUID 
		,CN_ITEMCODE_PARENT
		,CN_ITEMCODE
		,CN_F_QUANTITY
		,CN_DISPLAYNAME
		,CN_ORDER
		,CN_UNIT
		,CN_ISBORROW
		,0
		,CN_DT_CREATE
		,CN_DT_EFFECTIVE
		,CN_DT_EXPIRY
		,CN_DT_TOERP
		,CN_IS_TOERP
		,CN_DESC
		,CN_CREATE_BY
		,CN_CREATE_NAME
		,CN_CREATE_LOGIN
	FROM inserted
END;
GO