ALTER VIEW [DBO].[VIEW_ITEM_MAINTENANCE]
AS
SELECT
	  ITEM.CN_ID
	, ITEM.CN_CODE
	, ITEM.CN_ITEM_CODE
	, ITEM.CN_NAME
	, ITEM.CN_UNIT
	, ITEM.CN_WEIGHT
	, ITEM.CN_GG
	, ITEM.CN_SYS_NOTE
	, ITEM.CN_ITEM_PROLINE AS CN_PRODUCTLINECODE
	, ITEM.CN_IS_TOERP
	, ITEM.CN_DT_TOERP
	, CAST(ISNULL(ITEM.CN_PDM_CLS_ID,0) AS BIT) AS CN_IS_PDM
	, SUBSTRING((
		SELECT 
		',' + RTRIM(ITEMT.CN_NAME)
		FROM
		DBO.TN_80_APP_0000_ITEM_HLINK AS ITEMH 
		LEFT JOIN DBO.TN_50_DIC_0005_ITEMTYPE AS ITEMT ON ITEMT.CN_ID = ITEMH.CN_COMPONENT_OBJECT_ID AND ITEMH.CN_COMPONENT_CLASS_ID = 105
		WHERE ITEMH.CN_ID = ITEM.CN_ID AND ITEMH.CN_SYS_STATUS = 'Y'
		ORDER BY ITEMH.CN_COMPONENT_OBJECT_ID
		FOR XML PATH('')
	),2,100) AS CN_TYPENAMES
	, SUBSTRING((
		SELECT 
		',' + CAST(ITEMT.CN_ID AS VARCHAR)
		FROM
		DBO.TN_80_APP_0000_ITEM_HLINK AS ITEMH 
		LEFT JOIN DBO.TN_50_DIC_0005_ITEMTYPE AS ITEMT ON ITEMT.CN_ID = ITEMH.CN_COMPONENT_OBJECT_ID AND ITEMH.CN_COMPONENT_CLASS_ID = 105
		WHERE ITEMH.CN_ID = ITEM.CN_ID AND ITEMH.CN_SYS_STATUS = 'Y'
		ORDER BY ITEMH.CN_COMPONENT_OBJECT_ID
		FOR XML PATH('')
	),2,100) AS CN_TYPEIDS
FROM DBO.TN_80_APP_0000_ITEM AS ITEM
GO 

SELECT TOP 100 * 
FROM [VIEW_ITEM_MAINTENANCE]  
ORDER BY CN_ID DESC
 